theme: jekyll-theme-minimal
title: Muhammed Said Zatar's Portfolio
description: >- # this means to ignore newlines until "baseurl:"
  Welcome to my professional portfolio on GitHub Pages.
  Here is some information about my skills, experience, and projects.
github_username: muhammedzatar
